option(ENABLE_VPROC "Enable video process" ON)
if( ENABLE_VPROC )
    set(HAVE_VPROC true)
    add_definitions(-DHAVE_VPROC)
endif()

option(ENABLE_VPROC_VDPP "Enable video display post processor" OFF)
if( ENABLE_VPROC_VDPP )
    set(HAVE_VPROC_VDPP true)
    set(VPROC_VDPP vproc_vdpp)
    add_definitions(-DHAVE_VPROC_VDPP)
endif()
